package org.bkr.models;
// Generated 09 26, 18 5:30:50 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DailyDetails generated by hbm2java
 */
@Entity
@Table(name = "daily_details")
public class DailyDetail implements java.io.Serializable {

	private Long id;
	private DailyHeader dailyHeader;
	private TemplateDetail templateDetails;
	private int beginningInv;
	private int production;
	private int endingInv;
	private int tgafs;
	private int sales;
	private long amount;

	public DailyDetail() {
	}

	public DailyDetail(int beginningInv, int production, int endingInv, int tgafs, int sales, long amount) {
		this.beginningInv = beginningInv;
		this.production = production;
		this.endingInv = endingInv;
		this.tgafs = tgafs;
		this.sales = sales;
		this.amount = amount;
	}

	public DailyDetail(DailyHeader dailyHeader, TemplateDetail templateDetails, int beginningInv, int production,
			int endingInv, int tgafs, int sales, long amount) {
		this.dailyHeader = dailyHeader;
		this.templateDetails = templateDetails;
		this.beginningInv = beginningInv;
		this.production = production;
		this.endingInv = endingInv;
		this.tgafs = tgafs;
		this.sales = sales;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "daily_head_id")
	public DailyHeader getDailyHeader() {
		return this.dailyHeader;
	}

	public void setDailyHeader(DailyHeader dailyHeader) {
		this.dailyHeader = dailyHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "template_detail_id")
	public TemplateDetail getTemplateDetails() {
		return this.templateDetails;
	}

	public void setTemplateDetails(TemplateDetail templateDetails) {
		this.templateDetails = templateDetails;
	}

	@Column(name = "beginning_inv", nullable = false)
	public int getBeginningInv() {
		return this.beginningInv;
	}

	public void setBeginningInv(int beginningInv) {
		this.beginningInv = beginningInv;
	}

	@Column(name = "production", nullable = false)
	public int getProduction() {
		return this.production;
	}

	public void setProduction(int production) {
		this.production = production;
	}

	@Column(name = "ending_inv", nullable = false)
	public int getEndingInv() {
		return this.endingInv;
	}

	public void setEndingInv(int endingInv) {
		this.endingInv = endingInv;
	}

	@Column(name = "tgafs", nullable = false)
	public int getTgafs() {
		return this.tgafs;
	}

	public void setTgafs(int tgafs) {
		this.tgafs = tgafs;
	}

	@Column(name = "sales", nullable = false)
	public int getSales() {
		return this.sales;
	}

	public void setSales(int sales) {
		this.sales = sales;
	}

	@Column(name = "amount", nullable = false, precision = 10, scale = 0)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

}
