package org.bkr.models;
// Generated 09 26, 18 5:30:50 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DailyHeader generated by hbm2java
 */
@Entity
@Table(name = "daily_header")
public class DailyHeader implements java.io.Serializable {

	private Long id;
	private Date date;
	private Set<DailyDetail> dailyDetails = new HashSet<>();

	public DailyHeader() {
	}

	public DailyHeader(Date date) {
		this.date = date;
	}

	public DailyHeader(Date date, Set dailyDetailses) {
		this.date = date;
		this.dailyDetails = dailyDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dailyHeader")
	public Set<DailyDetail> getDailyDetailses() {
		return this.dailyDetails;
	}

	public void setDailyDetailses(Set<DailyDetail> dailyDetailses) {
		this.dailyDetails = dailyDetailses;
	}

}
