package org.bkr.models;
// Generated 09 26, 18 5:30:50 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TemplateDetails generated by hbm2java
 */
@Entity
@Table(name = "template_details")
public class TemplateDetail implements java.io.Serializable {

	private TemplateDetailsId id;
	private MasterBreadList masterBreadList;
	private Template template;
	private Set<DailyDetail> dailyDetails = new HashSet<>();

	public TemplateDetail() {
	}

	public TemplateDetail(TemplateDetailsId id, MasterBreadList masterBreadList, Template template) {
		this.id = id;
		this.masterBreadList = masterBreadList;
		this.template = template;
	}

	public TemplateDetail(TemplateDetailsId id, MasterBreadList masterBreadList, Template template,
			Set<DailyDetail> dailyDetailses) {
		this.id = id;
		this.masterBreadList = masterBreadList;
		this.template = template;
		this.dailyDetails = dailyDetailses;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "templateId", column = @Column(name = "template_id", nullable = false)),
			@AttributeOverride(name = "masterBreadId", column = @Column(name = "master_bread_id", nullable = false)) })
	public TemplateDetailsId getId() {
		return this.id;
	}

	public void setId(TemplateDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "master_bread_id", nullable = false, insertable = false, updatable = false)
	public MasterBreadList getMasterBreadList() {
		return this.masterBreadList;
	}

	public void setMasterBreadList(MasterBreadList masterBreadList) {
		this.masterBreadList = masterBreadList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "template_id", nullable = false, insertable = false, updatable = false)
	public Template getTemplates() {
		return this.template;
	}

	public void setTemplates(Template templates) {
		this.template = templates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "templateDetails")
	public Set<DailyDetail> getDailyDetailses() {
		return this.dailyDetails;
	}

	public void setDailyDetailses(Set<DailyDetail> dailyDetailses) {
		this.dailyDetails = dailyDetailses;
	}

}
