package org.bkr.models;
// Generated 09 26, 18 5:30:50 PM by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DailyHeader generated by hbm2java
 */
@Entity
@Table(name = "daily_header")
public class DailyHeader implements java.io.Serializable {

	private Long id;
	private Date date;
	private BigDecimal total;
	private BigDecimal expenses;
	private BigDecimal grandTotal;
	private BigDecimal remittance;
	private BigDecimal difference;
	private BigDecimal amExpenses;
	private BigDecimal pmExpenses;
	private BigDecimal amRemittance;
	private BigDecimal pmRemittance;
	private Set<DailyDetail> dailyDetails = new HashSet<>();

	public DailyHeader() {
	}

	public DailyHeader(Date date) {
		this.date = date;
	}

	public DailyHeader(Date date, Set dailyDetailses) {
		this.date = date;
		this.dailyDetails = dailyDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dailyHeader")
	public Set<DailyDetail> getDailyDetailses() {
		return this.dailyDetails;
	}

	public void setDailyDetailses(Set<DailyDetail> dailyDetailses) {
		this.dailyDetails = dailyDetailses;
	}

	@Column(name = "total", nullable = false, precision = 10, scale = 2)
	public BigDecimal getTotal() {
		return total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "expenses", nullable = false, precision = 10, scale = 2)
	public BigDecimal getExpenses() {
		return expenses;
	}

	public void setExpenses(BigDecimal expenses) {
		this.expenses = expenses;
	}

	@Column(name = "grand_total", nullable = false, precision = 10, scale = 2)
	public BigDecimal getGrandTotal() {
		return grandTotal;
	}

	public void setGrandTotal(BigDecimal grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "remittance", nullable = false, precision = 10, scale = 2)
	public BigDecimal getRemittance() {
		return remittance;
	}

	public void setRemittance(BigDecimal remittance) {
		this.remittance = remittance;
	}

	@Column(name = "difference", nullable = false, precision = 10, scale = 2)
	public BigDecimal getDifference() {
		return difference;
	}

	public void setDifference(BigDecimal difference) {
		this.difference = difference;
	}

	@Column(name = "am_expenses", nullable = false, precision = 10, scale = 2)
	public BigDecimal getAmExpenses() {
		return amExpenses;
	}

	public void setAmExpenses(BigDecimal amExpenses) {
		this.amExpenses = amExpenses;
	}

	@Column(name = "pm_expenses", nullable = false, precision = 10, scale = 2)
	public BigDecimal getPmExpenses() {
		return pmExpenses;
	}

	public void setPmExpenses(BigDecimal pmExpenses) {
		this.pmExpenses = pmExpenses;
	}

	@Column(name = "am_remittance", nullable = false, precision = 10, scale = 2)
	public BigDecimal getAmRemittance() {
		return amRemittance;
	}

	public void setAmRemittance(BigDecimal amRemittance) {
		this.amRemittance = amRemittance;
	}

	@Column(name = "pm_remittance", nullable = false, precision = 10, scale = 2)
	public BigDecimal getPmRemittance() {
		return pmRemittance;
	}

	public void setPmRemittance(BigDecimal pmRemittance) {
		this.pmRemittance = pmRemittance;
	}
	
	
	

}
