package org.bkr.models;
// Generated 09 26, 18 5:30:50 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TemplateDetailsId generated by hbm2java
 */
@Embeddable
public class TemplateDetailsId implements java.io.Serializable {

	private long templateId;
	private long masterBreadId;

	public TemplateDetailsId() {
	}

	public TemplateDetailsId(long templateId, long masterBreadId) {
		this.templateId = templateId;
		this.masterBreadId = masterBreadId;
	}

	@Column(name = "template_id", nullable = false)
	public long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(long templateId) {
		this.templateId = templateId;
	}

	@Column(name = "master_bread_id", nullable = false)
	public long getMasterBreadId() {
		return this.masterBreadId;
	}

	public void setMasterBreadId(long masterBreadId) {
		this.masterBreadId = masterBreadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TemplateDetailsId))
			return false;
		TemplateDetailsId castOther = (TemplateDetailsId) other;

		return (this.getTemplateId() == castOther.getTemplateId())
				&& (this.getMasterBreadId() == castOther.getMasterBreadId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (int) this.getTemplateId();
		result = 37 * result + (int) this.getMasterBreadId();
		return result;
	}

}
