package org.bkr.models;
// Generated 10 20, 18 7:24:40 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TemplateDetails generated by hbm2java
 */
@Entity
@Table(name = "template_details")
public class TemplateDetail implements java.io.Serializable {

	private Long id;
	private MasterBreadList masterBreadList;
	private Template template;
	private BigDecimal price;
	
	public TemplateDetail() {
	}

	public TemplateDetail(MasterBreadList masterBreadList, Template template) {
		this.masterBreadList = masterBreadList;
		this.template = template;
	}
	
	public TemplateDetail(long masterBreadId,long templateId)
	{
		this.masterBreadList=new MasterBreadList();
		this.masterBreadList.setId(masterBreadId);
		
		this.template=new Template();
		this.template.setId(templateId);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "master_bread_id", nullable = false)
	public MasterBreadList getMasterBreadList() {
		return this.masterBreadList;
	}

	public void setMasterBreadList(MasterBreadList masterBreadList) {
		this.masterBreadList = masterBreadList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "template_id", nullable = false)
	public Template getTemplate() {
		return this.template;
	}

	public void setTemplate(Template template) {
		this.template = template;
	}

	@Column(name = "price", precision = 10, scale = 2)
	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	
	

}
